x-service-templates:
  backend: &backend
    image: krymancer/rinha-2025-01-dotnet
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "80MB"
    networks:
      - backend
      - payment-processor
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/healthcheck || exit 1
      interval: 5m
      timeout: 3s
      retries: 3
      start_period: 2m

services:
  backend-1:
    <<: *backend
    container_name: backend-1
    hostname: backend-1
  backend-2:
    <<: *backend
    container_name: backend-2
    hostname: backend-2
  nginx:
    image: nginx
    volumes:
      - ./.conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:8080"
    depends_on:
      backend-1:
        condition: service_healthy
      backend-2:
        condition: service_healthy
    networks:
      - backend
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"
  database:
    image: postgres
    command: 'postgres -c max_connections=400 -c synchronous_commit=off -c fsync=off -c full_page_writes=off'
    networks:
      - payment-processor
    volumes:
      - ./.conf/postgres/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d db" ]
      interval: 1s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "140MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true