services:
  api1:
    build: ./backend
    container_name: api1
    hostname: api1
    environment:
      - SERVER_SOCKET_PATH=/tmp/api1.sock
      - DATABASE_SOCKET_PATH=/tmp/db.sock
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    volumes:
      - rb2025:/tmp/
    networks:
      - payment-processor
    depends_on:
      - database
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: 155MB

  api2:
    build: ./backend
    container_name: api2
    hostname: api2
    environment:
      - SERVER_SOCKET_PATH=/tmp/api2.sock
      - DATABASE_SOCKET_PATH=/tmp/db.sock
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    volumes:
      - rb2025:/tmp/
    networks:
      - payment-processor
    depends_on:
      - database
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: 155MB

  database:
    build:
      context: ./database-server
      dockerfile: Dockerfile.database
    container_name: database
    hostname: database
    environment:
      - DATABASE_SOCKET_PATH=/tmp/db.sock
    volumes:
      - rb2025:/tmp/
    networks:
      - payment-processor
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: 50MB

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - rb2025:/tmp/
    depends_on:
      - api1
      - api2
    networks:
      - payment-processor
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 40MB

volumes:
  rb2025:
    driver: local

networks:
  payment-processor:
    external: true
    driver: bridge